"""glacier remove project_id

Revision ID: db3ee7e5f4f2
Revises: cb6b5a832aa5
Create Date: 2025-12-10 21:05:21.062252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db3ee7e5f4f2"
down_revision: Union[str, Sequence[str], None] = "cb6b5a832aa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_glacier_project_id"), table_name="glacier")
    op.drop_constraint(op.f("glacier_project_id_fkey"), "glacier", type_="foreignkey")
    op.drop_column("glacier", "project_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "glacier",
        sa.Column("project_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("glacier_project_id_fkey"),
        "glacier",
        "project",
        ["project_id"],
        ["project_id"],
    )
    op.create_index(
        op.f("ix_glacier_project_id"), "glacier", ["project_id"], unique=False
    )
